project:
  type: book
  output-dir: docs
  
book:
  title: "Foraging manuscript data analysis"
  author: "Matt Green"
  date: now
  chapters:
    - index.qmd
    - part: Experiment One
      chapters: 
        - e1-ntrees.qmd
        - e1-nrevisits.qmd
        - e1-retrieval.qmd
        - e1-distance.qmd
        - e1-master-plot.qmd
    - part: Experiment Two
      chapters: 
        - e2-ntrees.qmd

format:
  html: 
    theme: 
      cosmo
    code-fold: true
    code-summary: "Show the code"
    # grid:
    #   sidebar-width: 300px
    #   body-width: 1200px
    #   margin-width: 150px
    #   gutter-width: 1.5rem
