project:
  type: book
  output-dir: docs
  
book:
  title: "foraging-manuscript-al23"
  author: "Jane Doe"
  date: "04/21/2023"
  chapters:
    - index.qmd
    - part: Experiment One
      chapters: 
        - e1-retrieval.qmd
    - part: Experiment Two
      chapters: 
        - e2-ntrees.qmd

format:
  html:
    theme: cosmo

