# Distance

The Euclidian distance between successive tree-visits, in units of pixels.

```{r setup, include=FALSE}
source("_libraries.R")
source("_prettify.R")
source("_plot_preferences.R")
knitr::opts_chunk$set(fig.path='e1_figures/')
knitr::opts_chunk$set(fig.width=7, fig.height=5)
options(dplyr.summarise.inform=F)
```

## E1 Distance - Prepare the data

Read the data and pre=process it.

```{r e1_ntrees_prep_data}
e1 <- readRDS("001-00-e1-data.RDS")

# remove things from the raw data to make it 
# suitable for this particular analysis

# remove samples that did not look at a tree
e1 <- e1 %>% filter(fl>0)

# remove the second (and any subsequent) *consecutive* duplicates
e1 <- e1 %>% 
  group_by(pp, rr, tb) %>% 
  filter(is.na(tl != lag(tl)) | tl != lag(tl)) %>% 
  ungroup()

# remove trials where they failed to get 10 fruit
e1 <- e1 %>% 
  group_by(pp, te) %>% 
  mutate(max_fr = max(fr)) %>% 
  ungroup() %>% 
  filter(max_fr==10)

# Euclid
e1 <- e1 
group_by(pp, resources, trial) %>% 
  mutate(itdist = round(sqrt((lead(xx)-xx)^2 + (lead(yy)-yy)^2), 2))

saveRDS(ntr, "e1_distance_data.rds")
```
